module.exports = function(sequelize, DataTypes) {
    return sequelize.define('surveys', {
        user_id: {type: DataTypes.STRING(36), primaryKey: true}, //CHAR(36)
        GEQ_rt1: DataTypes.INTEGER,
        GEQ1: DataTypes.INTEGER,
        GEQ2: DataTypes.INTEGER,
        GEQ3: DataTypes.INTEGER,
        GEQ4: DataTypes.INTEGER,
        GEQ5: DataTypes.INTEGER,
        GEQ6: DataTypes.INTEGER,
        GEQ7: DataTypes.INTEGER,
        GEQ8: DataTypes.INTEGER,
        GEQ9: DataTypes.INTEGER,
        GEQ_rt2: DataTypes.INTEGER,
        GEQ10: DataTypes.INTEGER,
        GEQ11: DataTypes.INTEGER,
        GEQ12: DataTypes.INTEGER,
        GEQ13: DataTypes.INTEGER,
        GEQ14: DataTypes.INTEGER,
        GEQ15: DataTypes.INTEGER,
        GEQ16: DataTypes.INTEGER,
        GEQ17: DataTypes.INTEGER,
        GEQ18: DataTypes.INTEGER,
        TLX_rt: DataTypes.INTEGER,
        mental_demand: DataTypes.INTEGER,
        physical_demand: DataTypes.INTEGER,
        temporal_demand: DataTypes.INTEGER,
        performance: DataTypes.INTEGER,
        effort: DataTypes.INTEGER,
        frustration: DataTypes.INTEGER,
        created_at: DataTypes.DATE,
    },
    {
        timestamps: true,
        updatedAt: false,
        deletedAt: false,
        freezeTableName: true,
        createdAt: 'created_at',
    });
}